### ISSUE TITLE
.DS_Store in lang folder throws error

### ISSUE THREAD

**Issue by APinchofDill** [AtomHash/evernode#44]
Output of error when a .DS_Store file is present
```
.DS_Store
['/srv/server/app/resources/lang']
Traceback (most recent call last):
  File "/srv/server/app/app.py", line 11, in <module>
    evernode_app = App(__name__)
  File "/usr/local/lib/python3.8/site-packages/evernode/classes/app.py", line 33, in __init__
    self.load_language_files()
  File "/usr/local/lib/python3.8/site-packages/evernode/classes/app.py", line 176, in load_language_files
    LoadLanguageFiles(self)()
  File "/usr/local/lib/python3.8/site-packages/evernode/classes/load_language_files.py", line 20, in __init__
    self.find_files()
  File "/usr/local/lib/python3.8/site-packages/evernode/classes/load_language_files.py", line 72, in find_files
    language=path.split("lang%s" % (os.sep), 1)[1].strip()
```

**Comment by APinchofDill** [comment]
Fixed in v1.4.1
